Revert "Updating builder-model to a newer of version 2.2.0-alpha1 (CL 1 of 2)."
Getting at runtime:
org.gradle.tooling.model.UnsupportedMethodException: Method public abstract java.io.File com.android.builder.model.AndroidBundle.getFolder() not found

This reverts commit 6a2a4eabd3c2d4649a749d4992706d8d3f753dc5.

Change-Id: I4af5f8be5ee6148d4b45e2d5c07193ea117febe2